<?php

namespace Database\Seeders;

use App\Models\ExplorePunePlace;
use Illuminate\Database\Seeder;

class ExplorePunePlaceSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            [
                'name' => 'Shreemant Dagdusheth Halwai Ganpati Temple',
                'category' => 'Famous Temple',
                'nearest_station' => 'PMR 23 — District Court',
                'distance_from_station' => 'Approx. 2 km — 25 min walk / 8 min by auto',
                'distance_note' => 'Auto rickshaw available from District Court station',
                'about' => "One of Pune's most celebrated temples, dedicated to Lord Ganesha and established in 1893 by Dagdusheth Halwai. The idol is adorned with gold ornaments and attracts thousands of devotees daily. A landmark destination during Ganesh Chaturthi, featuring grand cultural celebrations.",
                'highlights' => 'Established 1893 | Gold-adorned idol | Ganesh Chaturthi | Cultural events',
                'google_maps_link' => 'https://maps.google.com/?q=Dagdusheth+Halwai+Ganpati+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #7c3000 0%, #b45309 100%)',
                'sort_order' => 1,
            ],
            [
                'name' => 'Aga Khan Palace - Historical Monument',
                'category' => 'Heritage & History',
                'nearest_station' => 'PMR 20 — Baner',
                'distance_from_station' => '15 min auto-rickshaw',
                'distance_note' => 'Easily accessible by local transport',
                'about' => 'Built in 1892, Aga Khan Palace is a landmark of Indian history and a monument of love and compassion. It served as a prison for Mahatma Gandhi and Kasturba Gandhi during the freedom movement and is now a museum.',
                'highlights' => 'Gandhiji memorial | Italian arches | Manicured gardens | Historical museum',
                'google_maps_link' => 'https://maps.google.com/?q=Aga+Khan+Palace+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #064e3b 0%, #065f46 100%)',
                'sort_order' => 2,
            ],
            [
                'name' => 'Sinhagad Fort - Historic Hill Fort',
                'category' => 'Historic Fort & Trekking',
                'nearest_station' => 'PMR 01 — Hinjewadi Phase 3',
                'distance_from_station' => '45 min cab ride',
                'distance_note' => 'Accessible by cab/private vehicle',
                'about' => "Sinhagad Fort, meaning 'Lion's Fort', is a historic fortification located about 30 km south-west of Pune. Famous for the Battle of Sinhagad (1670), the fort offers panoramic views of the Sahyadri mountain range.",
                'highlights' => 'Panoramic Sahyadri views | Historic battle site | Trekking trails | Monsoon tourism',
                'google_maps_link' => 'https://maps.google.com/?q=Sinhagad+Fort+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #1c1917 0%, #44403c 100%)',
                'sort_order' => 3,
            ],
            [
                'name' => 'Parvati Hill - Temple Hill',
                'category' => 'Temple & Heritage',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '20 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'Parvati Hill is one of the oldest heritage structures in Pune, perched atop a hill 2,100 ft above sea level. The hilltop houses several ancient temples dedicated to Parvati, Vishnu, Kartikeya, and Devdeveshwar.',
                'highlights' => 'Panoramic city views | Ancient temples | Heritage hilltop | 108 stone steps',
                'google_maps_link' => 'https://maps.google.com/?q=Parvati+Hill+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #3b0764 0%, #4c1d95 100%)',
                'sort_order' => 4,
            ],
            [
                'name' => 'Shaniwar Wada - Fortification',
                'category' => 'Historical Monument',
                'nearest_station' => 'PMR 23 — District Court',
                'distance_from_station' => 'Approx. 2 km — 8 min by auto',
                'distance_note' => 'Auto rickshaw recommended from District Court station',
                'about' => "A magnificent 18th-century fortification and the historical seat of the Peshwa rulers of the Maratha Confederacy. Built in 1732 by Peshwa Bajirao I, the palace complex is one of Pune's most iconic landmarks and a symbol of Maratha heritage and architecture.",
                'highlights' => 'Built 1732 | Peshwa heritage | Maratha history | Sound & Light Show',
                'google_maps_link' => 'https://maps.google.com/?q=Shaniwar+Wada+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%)',
                'sort_order' => 5,
            ],
            [
                'name' => 'Rajiv Gandhi Zoological Park',
                'category' => 'Wildlife & Nature',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '20 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'Rajiv Gandhi Zoological Park in Katraj, Pune, is one of the most visited wildlife parks in Maharashtra. It houses leopards, bears, exotic birds, and a snake park spread across a large natural habitat.',
                'highlights' => 'Snake park | Katraj Lake | Diverse wildlife | Family attraction',
                'google_maps_link' => 'https://maps.google.com/?q=Rajiv+Gandhi+Zoological+Park+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #14532d 0%, #16a34a 100%)',
                'sort_order' => 6,
            ],
            [
                'name' => 'Osho Ashram - Spiritual Retreat',
                'category' => 'Spirituality & Wellness',
                'nearest_station' => 'PMR 20 — Baner',
                'distance_from_station' => '20 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'Osho International Meditation Resort is a unique meditative retreat in Koregaon Park, Pune. Spanning 40 acres, it offers a blend of meditation, relaxation, and personal growth programs attracting visitors from around the world.',
                'highlights' => 'Meditation resort | Pyramid auditorium | World-class facilities | International visitors',
                'google_maps_link' => 'https://maps.google.com/?q=Osho+Ashram+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #451a03 0%, #92400e 100%)',
                'sort_order' => 7,
            ],
            [
                'name' => 'Pune Okayama Friendship Garden',
                'category' => 'Gardens & Nature',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '15 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'The Pune Okayama Friendship Garden, also known as Pu La Deshpande Garden, is a beautifully designed Japanese-inspired garden. Built to commemorate the friendship between Pune and Okayama, Japan.',
                'highlights' => 'Japanese-style garden | Friendship bridge | Seasonal flowers | Peaceful ambience',
                'google_maps_link' => 'https://maps.google.com/?q=Pune+Okayama+Friendship+Garden',
                'fallback_bg' => 'linear-gradient(135deg, #052e16 0%, #166534 100%)',
                'sort_order' => 8,
            ],
            [
                'name' => 'Kasba Ganpati Temple - Heritage Site',
                'category' => 'Famous Temple',
                'nearest_station' => 'PMR 23 — District Court',
                'distance_from_station' => 'Approx. 1.2 km — 17 min walk / 5 min by auto',
                'distance_note' => 'Auto rickshaw available from District Court station',
                'about' => "One of Pune's oldest and most revered Ganpati temples, Kasba Ganpati is the Gramadevata (presiding deity) of Pune. The temple holds immense religious significance and is the first Manacha Ganpati — the temple of highest honour during Ganesh Chaturthi celebrations.",
                'highlights' => 'Gramadevata of Pune | First Manacha Ganpati | Ganesh Chaturthi | Walking distance',
                'google_maps_link' => 'https://maps.google.com/?q=Kasba+Ganpati+Temple+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #4a1942 0%, #86198f 100%)',
                'sort_order' => 9,
            ],
            [
                'name' => 'National War Museum - Pune',
                'category' => 'Museums & Defence',
                'nearest_station' => 'PMR 23 — Shivajinagar District Court',
                'distance_from_station' => '5 min walk',
                'distance_note' => 'Directly accessible from station exit',
                'about' => "The National War Museum in Pune is a tribute to India's armed forces, displaying war memorabilia, tanks, aircraft, and weapons from various conflicts. A must-visit for history and defence enthusiasts.",
                'highlights' => 'War memorabilia | Tanks & aircraft | Defence history | Patriotic landmark',
                'google_maps_link' => 'https://maps.google.com/?q=National+War+Museum+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #1c1917 0%, #57534e 100%)',
                'sort_order' => 10,
            ],
            [
                'name' => 'Lohagad Fort - Trekking Destination',
                'category' => 'Historic Fort & Trekking',
                'nearest_station' => 'PMR 01 — Hinjewadi Phase 3',
                'distance_from_station' => '60 min cab ride',
                'distance_note' => 'Accessible by cab/private vehicle',
                'about' => 'Lohagad Fort is a historic hill fort near Malavli at an altitude of 3,389 feet. Famous for its scenic beauty and Maratha heritage, it was held by Shivaji Maharaj and later by Nana Fadnavis.',
                'highlights' => 'Hill trekking | Panoramic views | Historic Maratha fort | Monsoon greenery',
                'google_maps_link' => 'https://maps.google.com/?q=Lohagad+Fort+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #0f172a 0%, #334155 100%)',
                'sort_order' => 11,
            ],
            [
                'name' => 'Chaturshringi Temple - Sacred Site',
                'category' => 'Famous Temple & Hilltop Shrine',
                'nearest_station' => 'PMR 17 — Aundh',
                'distance_from_station' => 'Approx. 3 km — 10 min by auto',
                'distance_note' => 'Auto rickshaw recommended from Aundh station',
                'about' => 'A revered hilltop temple dedicated to Goddess Chaturshrungi, the presiding deity of Pune, located on Senapati Bapat Road. The temple sits on a mountain with four peaks and requires climbing 170 steps to reach the shrine. The natural idol (swayambhu) is especially celebrated during Navratri.',
                'highlights' => 'Presiding deity of Pune | 170 steps | Navratri festival | Hilltop views',
                'google_maps_link' => 'https://maps.google.com/?q=Chaturshringi+Temple+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #7f1d1d 0%, #dc2626 100%)',
                'sort_order' => 12,
            ],
            [
                'name' => 'Saras Baug Garden - Ganesh Temple',
                'category' => 'Gardens & Temples',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '20 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'Saras Baug is a beautiful garden in Pune, known for its Prasanna Ganapati temple, a serene lake, and lush greenery. A popular recreational spot for families and devotees alike.',
                'highlights' => 'Prasanna Ganapati temple | Scenic lake | Lush gardens | Family picnic spot',
                'google_maps_link' => 'https://maps.google.com/?q=Saras+Baug+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #1e1b4b 0%, #4338ca 100%)',
                'sort_order' => 13,
            ],
            [
                'name' => 'Empress Botanical Garden',
                'category' => 'Gardens & Nature',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '10 min walk',
                'distance_note' => 'Short walk from station exit',
                'about' => 'The Empress Botanical Garden is a 39-acre botanical garden in Pune established in 1881. Home to a rich variety of trees, plants, and exotic species, it is a green oasis in the heart of the city.',
                'highlights' => 'Exotic plant collection | 39-acre green space | Heritage botanical garden | Family park',
                'google_maps_link' => 'https://maps.google.com/?q=Empress+Botanical+Garden+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #134e4a 0%, #0d9488 100%)',
                'sort_order' => 14,
            ],
            [
                'name' => 'Vishrambaug Wada - Peshwa Palace',
                'category' => 'Heritage & History',
                'nearest_station' => 'PMR 23 — Shivajinagar District Court',
                'distance_from_station' => '10 min walk',
                'distance_note' => 'Short walk from station exit',
                'about' => 'Vishrambaug Wada is a historic Peshwa palace in Pune, known for its exquisite wooden carvings and Peshwa-era architecture. Built in 1807 by Peshwa Baji Rao II, it is now a heritage site under the Archaeological Survey of India.',
                'highlights' => 'Peshwa-era architecture | Wooden carvings | Heritage palace | Cultural significance',
                'google_maps_link' => 'https://maps.google.com/?q=Vishrambaug+Wada+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #431407 0%, #c2410c 100%)',
                'sort_order' => 15,
            ],
            [
                'name' => 'Bund Garden - River Park',
                'category' => 'Parks & Recreation',
                'nearest_station' => 'PMR 21 — Aundh',
                'distance_from_station' => '25 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => 'Bund Garden is a charming riverside park in Pune along the Mula-Mutha River. A popular recreational destination featuring lush lawns, boating facilities, and a pleasant riverside ambience.',
                'highlights' => 'Riverside park | Boating facilities | Lush lawns | Picnic destination',
                'google_maps_link' => 'https://maps.google.com/?q=Bund+Garden+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #042f2e 0%, #0f766e 100%)',
                'sort_order' => 16,
            ],
            [
                'name' => 'Pune Railway Station - Heritage',
                'category' => 'Heritage & Transport',
                'nearest_station' => 'PMR 23 — Shivajinagar District Court',
                'distance_from_station' => '15 min walk',
                'distance_note' => 'Short walk from station exit',
                'about' => 'Pune Railway Station, formally known as Pune Junction, is a historic railway station and one of the busiest in Maharashtra. Its classic colonial architecture and strategic location make it a landmark of Pune.',
                'highlights' => 'Colonial architecture | Busy transit hub | Heritage building | City gateway',
                'google_maps_link' => 'https://maps.google.com/?q=Pune+Railway+Station',
                'fallback_bg' => 'linear-gradient(135deg, #1e3a5f 0%, #0369a1 100%)',
                'sort_order' => 17,
            ],
            [
                'name' => 'Taljai Hill - Nature Reserve',
                'category' => 'Nature Reserve & Trekking',
                'nearest_station' => 'PMR 22 — Deccan Gymkhana',
                'distance_from_station' => '30 min auto-rickshaw',
                'distance_note' => 'Accessible by local transport',
                'about' => "Taljai Hill is a nature reserve and forest area in Pune, offering scenic trekking trails and a peaceful environment away from the city's bustle. Home to diverse flora and fauna, it is a nature lover's paradise.",
                'highlights' => 'Nature trails | Panoramic city views | Biodiversity | Morning walks',
                'google_maps_link' => 'https://maps.google.com/?q=Taljai+Hill+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #14532d 0%, #4ade80 100%)',
                'sort_order' => 18,
            ],
            [
                'name' => 'Phursungi Village - Rural Charm',
                'category' => 'Rural & Cultural',
                'nearest_station' => 'PMR 01 — Hinjewadi Phase 3',
                'distance_from_station' => '45 min cab ride',
                'distance_note' => 'Accessible by cab/private vehicle',
                'about' => 'Phursungi Village offers a glimpse into the rural heritage of Pune, with traditional architecture, local festivals, and agrarian culture. It represents the cultural roots of the region amidst the growing urban landscape.',
                'highlights' => 'Rural heritage | Traditional culture | Local festivals | Agrarian landscape',
                'google_maps_link' => 'https://maps.google.com/?q=Phursungi+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #422006 0%, #d97706 100%)',
                'sort_order' => 19,
            ],
            [
                'name' => 'Khadakwasla Dam - Scenic Reservoir',
                'category' => 'Lakes & Reservoirs',
                'nearest_station' => 'PMR 01 — Hinjewadi Phase 3',
                'distance_from_station' => '50 min cab ride',
                'distance_note' => 'Accessible by cab/private vehicle',
                'about' => 'Khadakwasla Dam is a scenic reservoir located near Pune, known for its picturesque surroundings and stunning views of the Sahyadri hills. It is one of the main water sources for Pune and a popular picnic destination.',
                'highlights' => 'Scenic reservoir | Sahyadri backdrop | Picnic destination | Water sports',
                'google_maps_link' => 'https://maps.google.com/?q=Khadakwasla+Dam+Pune',
                'fallback_bg' => 'linear-gradient(135deg, #0c4a6e 0%, #0ea5e9 100%)',
                'sort_order' => 20,
            ],
        ];

        foreach ($places as $place) {
            ExplorePunePlace::firstOrCreate(['name' => $place['name']], $place);
        }
    }
}
