<?php

return [
    'stations' => [
        [
            'code' => 'PMR 1',
            'name' => 'Maan',
            'slug' => 'pmr-1',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'TCS, Megapolis'],
                ['gate' => 'Gate 02', 'landmarks' => 'Eon Homes, Tech Mahindra'],
                ['gate' => 'Gate 03', 'landmarks' => 'Coming Soon'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Ground to Platform'],
                ['name' => 'Lift 4', 'level' => 'Ground to Platform'],
                ['name' => 'Lift 8', 'level' => 'Mezzanine to Platform'],
                ['name' => 'Lift 9', 'level' => 'Mezzanine to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Mezzanine'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Mezzanine'],
                ['name' => 'Escalator 3', 'level' => 'Mezzanine to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Mezzanine to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Mezzanine'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/XnfxergPfyJ1CQLPH',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.886270487513!2d73.6879852!3d18.5791654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb9d74a70789%3A0x9d81e66776f73217!2sMaan!5e0!3m2!1sen!2sin!4v1781335095071!5m2!1sen!2sin" style="border:0; width:100%; height:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['Megapolis Residential', 'Pawar Public School', 'TCS', 'Tech Mahindra'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Farmazia Hospital', 'distance' => '2.4 km', 'walking' => '29 min', 'car' => '8 min'],
                ['type' => 'Police Station', 'name' => 'Hinjewadi Police Station, Pimpri-Chinchwad Police Commissionerate', 'distance' => '3.1 km', 'walking' => '37 min', 'car' => '10 min'],
                ['type' => 'Fire Brigade', 'name' => 'Hinjewadi Fire Station, PCMC Fire Brigade', 'distance' => '4.4 km', 'walking' => '54 min', 'car' => '12 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => 'Pune International Airport', 'distance' => '27 km', 'car' => '50 min'],
                ['type' => 'Railway Station', 'name' => 'Pune Junction Railway Station', 'distance' => '23 km', 'car' => '45 min'],
            ],
        ],
        [
            'code' => 'PMR 2',
            'name' => 'Maan – MIDC Circle, Phase II',
            'slug' => 'pmr-2',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Embassy Quadron'],
                ['gate' => 'Gate 02', 'landmarks' => 'Maan Depot'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'U Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/ZfIlIqPnqmFYXeTR6',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.7751596828357!2d73.69505360000001!3d18.5841727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb8a339efbdd%3A0x4a4ebb1c354390e!2sMaan%20-%20MIDC%20Circle%2C%20Phase%20II!5e0!3m2!1sen!2sin!4v1781335454029!5m2!1sen!2sin"  style="border:0; width:100%; height:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['Quadron Park', 'MIDC', 'Vedant Hospital'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Ruby Hall Clinic, Hinjewadi', 'distance' => '1.1 km', 'walking' => '14 min', 'car' => '5 min'],
                ['type' => 'Police Station', 'name' => 'Hinjewadi Police Station, PCMC', 'distance' => '1.4 km', 'walking' => '17 min', 'car' => '6 min'],
                ['type' => 'Fire Brigade', 'name' => 'Hinjewadi Fire Station, PCMC', 'distance' => '3.7 km', 'walking' => '44 min', 'car' => '10 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '25 km', 'car' => '48 min'],
                ['type' => 'Railway Station', 'name' => 'Pune Junction Railway Station', 'distance' => '21 km', 'car' => '42 min'],
            ],
        ],
        [
            'code' => 'PMR 3',
            'name' => 'Maan Bus Depot',
            'slug' => 'pmr-3',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Dohler'],
                ['gate' => 'Gate 02', 'landmarks' => 'Abhay Bio CNG Pvt Ltd, SWM Plant'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Not Available'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/8vd0NjXJUtprSpGfl',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.6924840764004!2d73.7023337!3d18.5878977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bbaef49a0f5b%3A0x845269d08e694b!2sMaan%20Bus%20Depot!5e0!3m2!1sen!2sin!4v1781335525386!5m2!1sen!2sin"  style="border:0; width:100%; height:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['Quadron Park', 'MIDC', 'Vedant Hospital'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'LifeTree Hospital', 'distance' => '1.9 km', 'walking' => '23 min', 'car' => '6 min'],
                ['type' => 'Police Station', 'name' => 'Hinjewadi Police Station, PCMC', 'distance' => '2.0 km', 'walking' => '24 min', 'car' => '7 min'],
                ['type' => 'Fire Brigade', 'name' => 'Hinjewadi Fire Station, PCMC', 'distance' => '4.1 km', 'walking' => '49 min', 'car' => '11 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '26 km', 'car' => '49 min'],
                ['type' => 'Railway Station', 'name' => 'Pune Junction Railway Station', 'distance' => '22 km', 'car' => '43 min'],
            ],
        ],
        [
            'code' => 'PMR 4',
            'name' => 'Hinjawadi Phase-II Circle-II',
            'slug' => 'pmr-4',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Infosys'],
                ['gate' => 'Gate 02', 'landmarks' => 'TCG International Biotech Park'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Not Available'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/oXKoF1pCio21ZOx6u',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.546392176248!2d73.7096912!3d18.594478199999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb15a20a07ff%3A0xef444ba1c39b5eca!2sHinjawadi%20Phase-II%20Circle-II!5e0!3m2!1sen!2sin!4v1781335609371!5m2!1sen!2sin" style="border:0; width:100%; height:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['Vedant Hospital', 'Hinjewadi Police Station'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Hinjewadi Superspeciality Hospital', 'distance' => '950 m', 'walking' => '11 min', 'car' => '4 min'],
                ['type' => 'Police Station', 'name' => 'Hinjewadi Police Station, PCMC', 'distance' => '1.2 km', 'walking' => '15 min', 'car' => '5 min'],
                ['type' => 'Fire Brigade', 'name' => 'Hinjewadi Fire Station, PCMC', 'distance' => '3.4 km', 'walking' => '41 min', 'car' => '9 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '24 km', 'car' => '46 min'],
                ['type' => 'Railway Station', 'name' => 'Pune Junction Railway Station', 'distance' => '20 km', 'car' => '40 min'],
            ],
        ],
        [
            'code' => 'PMR 5',
            'name' => 'Hinjawadi Phase-II Circle-I',
            'slug' => 'pmr-5',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Wipro, Infosys'],
                ['gate' => 'Gate 02', 'landmarks' => 'Ibys Hotel'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Blossom Public School', 'Mumbai Pune National Highway'],
            'mapKey' => 'https://share.google/lF0PubnVH2ddqAZtj',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7562.997850326707!2d73.71726319999999!3d18.5966158!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bbaea18f7be3%3A0xb4c315fb1135dfe!2sHinjawadi%20Phase-II%20Circle-I!5e0!3m2!1sen!2sin!4v1781335651479!5m2!1sen!2sin"  style="border:0;width: 100%;height:100%" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Surya Mother & Child Super Speciality Hospital', 'distance' => '850 m', 'walking' => '10 min', 'car' => '4 min'],
                ['type' => 'Police Station', 'name' => 'Wakad Police Station, Pimpri-Chinchwad Police Commissionerate', 'distance' => '950 m', 'walking' => '11 min', 'car' => '5 min'],
                ['type' => 'Fire Brigade', 'name' => 'Wakad Fire Station, PCMC Fire Brigade', 'distance' => '1.7 km', 'walking' => '21 min', 'car' => '6 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '19 km', 'car' => '36 min'],
                ['type' => 'Railway Station', 'name' => 'Pimpri Railway Station', 'distance' => '11 km', 'car' => '24 min'],
            ],
        ],
        [
            'code' => 'PMR 6',
            'name' => 'Padmabhushan Chowk',
            'slug' => 'pmr-6',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Lalit Estate'],
                ['gate' => 'Gate 02', 'landmarks' => 'Balewadi Phata'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Not Available'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Hinjewadi Lake', 'Laxmi Chowk'],
            'mapKey' => 'https://share.google/IGVsiK3FZzJ7pFWz5',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.543918585615!2d73.72743790000001!3d18.5945896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb8a7771c88d%3A0x15a214daba4a10ba!2sPadmabhushan%20Chowk!5e0!3m2!1sen!2sin!4v1781335850343!5m2!1sen!2sin"  style="border:0; width:100%;height:100%" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Aundh Institute of Medical Sciences', 'distance' => '2.0 km', 'walking' => '24 min', 'car' => '7 min'],
                ['type' => 'Police Station', 'name' => 'Baner Police Station, Pune City Police', 'distance' => '1.8 km', 'walking' => '22 min', 'car' => '6 min'],
                ['type' => 'Fire Brigade', 'name' => 'Aundh Fire Station, Pune Municipal Corporation', 'distance' => '3.0 km', 'walking' => '36 min', 'car' => '9 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '18 km', 'car' => '34 min'],
                ['type' => 'Railway Station', 'name' => 'Shivajinagar Railway Station', 'distance' => '14 km', 'car' => '28 min'],
            ],
        ],
        [
            'code' => 'PMR 7',
            'name' => 'Shree Shiv Chhatrapati Shivaji Maharaj Chowk, Hinjawadi',
            'slug' => 'pmr-7',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Shivaji Chowk'],
                ['gate' => 'Gate 02', 'landmarks' => 'Hinjewadi Village'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Infotech Park', 'Rajiv Gandhi IT Park'],
             'mapKey' => 'https://share.google/G8uaRUO1lqAa1SwJC',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.5928792541904!2d73.7374066!3d18.592384499999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb22fc3341e1%3A0xbfca0055904ac3e5!2sShree%20Shiv%20Chhatrapati%20Shivaji%20Maharaj%20Chowk%2C%20Hinjawadi!5e0!3m2!1sen!2sin!4v1781335975073!5m2!1sen!2sin" style="border:0;width:100%;height:100%" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Manipal Hospitals, Baner', 'distance' => '1.5 km', 'walking' => '18 min', 'car' => '5 min'],
                ['type' => 'Police Station', 'name' => 'Hinjewadi Police Station, PCMC', 'distance' => '1.2 km', 'walking' => '14 min', 'car' => '5 min'],
                ['type' => 'Fire Brigade', 'name' => 'Hinjewadi Fire Station, PCMC', 'distance' => '3.0 km', 'walking' => '36 min', 'car' => '9 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '18 km', 'car' => '34 min'],
                ['type' => 'Railway Station', 'name' => 'Shivajinagar Railway Station', 'distance' => '14 km', 'car' => '28 min'],
            ],
        ],
        [
            'code' => 'PMR 8',
            'name' => 'Hinjawadi Phase - I',
            'slug' => 'pmr-8',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'HP Petrol Pump'],
                ['gate' => 'Gate 02', 'landmarks' => 'Wakad Road'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Blossom Public School', 'Mumbai Pune National Highway'],
             'mapKey' => 'https://share.google/ZeeA0MCLFktbr2z47',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.6255794892677!2d73.746285!3d18.5909116!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bb0eb1d3e241%3A0x1fb9fe588be36742!2sHinjawadi%20Phase%20-%20I!5e0!3m2!1sen!2sin!4v1781336092326!5m2!1sen!2sin" style="border:0;height:100%;width:100%" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Surya Mother & Child Super Speciality Hospital', 'distance' => '850 m', 'walking' => '10 min', 'car' => '4 min'],
                ['type' => 'Police Station', 'name' => 'Wakad Police Station, Pimpri-Chinchwad Police Commissionerate', 'distance' => '950 m', 'walking' => '11 min', 'car' => '5 min'],
                ['type' => 'Fire Brigade', 'name' => 'Wakad Fire Station, PCMC Fire Brigade', 'distance' => '1.7 km', 'walking' => '21 min', 'car' => '6 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '19 km', 'car' => '36 min'],
                ['type' => 'Railway Station', 'name' => 'Pimpri Railway Station', 'distance' => '11 km', 'car' => '24 min'],
            ],
        ],
        [
            'code' => 'PMR 9',
            'name' => 'Wakad Chowk',
            'slug' => 'pmr-9',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Mumbai Pune Highway'],
                ['gate' => 'Gate 02', 'landmarks' => 'Bhujbal Vasti'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Blossom Public School', 'Mumbai Pune National Highway'],
            //  'mapKey' => '',
            // 'embedMapUrl' => '',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Surya Mother & Child Super Speciality Hospital', 'distance' => '850 m', 'walking' => '10 min', 'car' => '4 min'],
                ['type' => 'Police Station', 'name' => 'Wakad Police Station, Pimpri-Chinchwad Police Commissionerate', 'distance' => '950 m', 'walking' => '11 min', 'car' => '5 min'],
                ['type' => 'Fire Brigade', 'name' => 'Wakad Fire Station, PCMC Fire Brigade', 'distance' => '1.7 km', 'walking' => '21 min', 'car' => '6 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '19 km', 'car' => '36 min'],
                ['type' => 'Railway Station', 'name' => 'Pimpri Railway Station', 'distance' => '11 km', 'car' => '24 min'],
            ],
        ],
        [
            'code' => 'PMR 10',
            'name' => 'Shree Shiv Chhatrapati Sports Complex, Mahalunge',
            'slug' => 'pmr-10',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => '7 Avenues'],
                ['gate' => 'Gate 02', 'landmarks' => 'Balewadi Stadium'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Available — Paid area beside Station Control Room'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/1CCNn4z2tm4HuYTNr',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.880681575983!2d73.7617446!3d18.5794173!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b9dd9ecc14cb%3A0x9b2a2cdebc5e1ee0!2sShree%20Shiv%20Chhatrapati%20Sports%20Complex%2C%20Mahalunge!5e0!3m2!1sen!2sin!4v1781336360160!5m2!1sen!2sin" style="border:0;width:100%;height:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['PICT Model School', 'Manipal Hospital'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Manipal Hospitals, Baner', 'distance' => '1.2 km', 'walking' => '15 min', 'car' => '5 min'],
                ['type' => 'Police Station', 'name' => 'Baner Police Station, Pune City Police', 'distance' => '2.1 km', 'walking' => '26 min', 'car' => '7 min'],
                ['type' => 'Fire Brigade', 'name' => 'Aundh Fire Station, Pune Municipal Corporation', 'distance' => '2.9 km', 'walking' => '35 min', 'car' => '9 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '18 km', 'car' => '34 min'],
                ['type' => 'Railway Station', 'name' => 'Shivajinagar Railway Station', 'distance' => '14 km', 'car' => '28 min'],
            ],
        ],
        [
            'code' => 'PMR 11',
            'name' => 'Mitcon Balewadi',
            'slug' => 'pmr-11',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Amartech Park, MIS School'],
                ['gate' => 'Gate 02', 'landmarks' => 'Nic Mar'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Not Available'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'mapKey' => 'https://share.google/24DJLDRCMdEF8DELK',
            'embedMapUrl' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3781.9792966012933!2d73.7660563!3d18.5749721!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b92e54ddc343%3A0x9acb2a5deda45404!2sMitcon%20Balewadi!5e0!3m2!1sen!2sin!4v1781336437556!5m2!1sen!2sin" style="border:0;height:100%;width:100%" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
            'nearbyPlaces' => ['Aram Tech Park', 'NICMAR University', 'Mahalunge (Ozon) Hospital'],
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Jupiter Hospital', 'distance' => '1.4 km', 'walking' => '17 min', 'car' => '5 min'],
                ['type' => 'Police Station', 'name' => 'Baner Police Station, Pune City Police', 'distance' => '1.9 km', 'walking' => '23 min', 'car' => '7 min'],
                ['type' => 'Fire Brigade', 'name' => 'Aundh Fire Station, Pune Municipal Corporation', 'distance' => '3.1 km', 'walking' => '37 min', 'car' => '9 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '17 km', 'car' => '32 min'],
                ['type' => 'Railway Station', 'name' => 'Shivajinagar Railway Station', 'distance' => '13 km', 'car' => '26 min'],
            ],
        ],
        [
            'code' => 'PMR 12',
            'name' => 'R K Laxman Museum Balewadi',
            'slug' => 'pmr-12',
            'entrances' => [
                ['gate' => 'Gate 01', 'landmarks' => 'Ridhi Sidhi Society, Smart Works'],
                ['gate' => 'Gate 02', 'landmarks' => 'RK Laxman Museum'],
            ],
            'platforms' => [
                ['number' => 'Platform 1', 'direction' => 'Civil Court (Down Line)'],
                ['number' => 'Platform 2', 'direction' => 'Maan Depot (Up Line)'],
            ],
            'liftsEscalators' => [
                ['name' => 'Lift 1', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 2', 'level' => 'Unpaid — Ground to Concourse'],
                ['name' => 'Lift 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Lift 4', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 1', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 2', 'level' => 'Ground to Unpaid Concourse'],
                ['name' => 'Escalator 3', 'level' => 'Paid — Concourse to Platform'],
                ['name' => 'Escalator 4', 'level' => 'Paid — Concourse to Platform'],
            ],
            'facilities' => [
                ['name' => 'Restrooms / Toilets', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'First Aid', 'location' => 'Paid area beside Station Control Room'],
                ['name' => 'Wheelchair', 'location' => 'First Aid Room'],
                ['name' => 'Parking', 'location' => 'Not Available'],
                ['name' => 'Drinking Water', 'location' => 'Paid area beside Station Control Room'],
            ],
            'nearbyPlaces' => ['Mahalunge (Ozon) Hospital', 'Manipal Hospital'],
            'mapKey' => '',
            'embedMapUrl' => '',
            'emergency' => [
                ['type' => 'Hospital', 'name' => 'Accord Multispeciality Hospital', 'distance' => '950 m', 'walking' => '12 min', 'car' => '4 min'],
                ['type' => 'Police Station', 'name' => 'Baner Police Station, Pune City Police', 'distance' => '1.7 km', 'walking' => '21 min', 'car' => '6 min'],
                ['type' => 'Fire Brigade', 'name' => 'Aundh Fire Station, Pune Municipal Corporation', 'distance' => '2.7 km', 'walking' => '33 min', 'car' => '8 min'],
            ],
            'transport' => [
                ['type' => 'Airport', 'name' => '—', 'distance' => '16 km', 'car' => '30 min'],
                ['type' => 'Railway Station', 'name' => 'Shivajinagar Railway Station', 'distance' => '12 km', 'car' => '24 min'],
            ],
        ],
        ['code' => 'PMR 13', 'name' => 'Balewadi High Street', 'slug' => 'pmr-13', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => 'https://share.google/ICNn4z2tm4HuYTNr', 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 14', 'name' => 'Balewadi Phata', 'slug' => 'pmr-14', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 15', 'name' => 'Baner Gaon', 'slug' => 'pmr-15', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 16', 'name' => 'Baner Pashan Link Road', 'slug' => 'pmr-16', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 17', 'name' => 'Aundh', 'slug' => 'pmr-17', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 18', 'name' => 'Sakalnagar', 'slug' => 'pmr-18', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 19', 'name' => 'Savitribai Phule Pune University', 'slug' => 'pmr-19', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 20', 'name' => 'Bhosalenagar – RBI', 'slug' => 'pmr-20', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 21', 'name' => 'Agriculture College', 'slug' => 'pmr-21', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 22', 'name' => 'Shivaji Nagar', 'slug' => 'pmr-22', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
        ['code' => 'PMR 23', 'name' => 'District Court, Pune', 'slug' => 'pmr-23', 'entrances' => [], 'platforms' => [], 'liftsEscalators' => [], 'facilities' => [], 'mapKey' => null, 'nearbyPlaces' => [], 'emergency' => [], 'transport' => []],
    ],
];
